- name: Patching | Include {{ ansible_os_family }} Family Tasks
  include_tasks: "apt.yml"
  when: ansible_os_family == "Debian"

- name: Patching | Include {{ ansible_os_family }} Family Tasks
  include_tasks: "dnf.yml"
  when: ansible_os_family == "RedHat"

- name: Patching | FreeBSD Tasks
  include_tasks: "freebsd.yml"
  when: ansible_os_family == "FreeBSD"
